### ISSUE TITLE
android php compatibility with this library support ?

### ISSUE THREAD

**Issue by achinverma** [tozny/java-aes-crypto#16]
hi, i want to use this library in my php code , so please can you help to implement this library in php side ?

**Comment by SyntaxPolice** [comment]
Hi Achinverma. Thanks for your interest in our library. We don't have a PHP implementation. Are you looking for something in PHP that will be compatible (e.g. on the server side), or just something to perform similar functionality (encrypting strings).

thanks,

  isaac

**Comment by achinverma** [comment]
hi @SyntaxPolice i am looking for a library which is compatible  with both android and php server side for encrypting and decrypting strings , please let me know if you know this kind of library.

**Comment by SyntaxPolice** [comment]
Achinverma. Sorry I hadn't gotten back to you. I didn't realize this issue was still open after Aug. 20.

We don't know if a PHP library that has the same functionality. Implementing one may or may not be difficult, depending on whether PHP crypto libraries offer the same ciphers and modes. In practice, we had tried to implement a compatible library in Javascript and found it challenging because of the restrictions in many languages in the availability of aes modes.

It may be that you are looking for something more like our upcoming product tozny.com/e3db. If that looks interesting, please sign up for the pilot.

thanks,

  isaac
