### ISSUE TITLE
Security alert on our production app on google play console

### ISSUE THREAD

**Issue by ashishdimi09** [tozny/java-aes-crypto#48]
Hi,
 
We are seeing a warning on our production app on google play console. The warning states:

> Security alert
> Your app contains unsafe cryptographic encryption patterns. Please see this Google Help Center article for details.
> Vulnerable classes: com.xxx.xxx.android.AesCbcWithIntegrity
> Affects APK version 10819.

The article the warning is referring to https://support.google.com/faqs/answer/9450925

> Remediation
> for Unsafe Cryptographic Encryption - Google HelpThis information is intended for developers with app(s) that contain unsafe cryptographic encryption patterns. That is, a ciphertext is generated with a statically computed secret key, salt, or initiasupport.google.com

Can someone help me to resolve this Security alert warning?

**Comment by SyntaxPolice** [comment]
This is an interesting error. We have not heard anyone else report this.
Our library does not use static keys as you probably know. It possible that
some of the backward compatibility code that we provide for older versions
of Android are confusing the scanner.

Or you may be using our library in such a way that you are using static
keys. if you can share example code for how use the libraries we might be
able to help you track it down.

**Comment by SyntaxPolice** [comment]
You can send me example code privately if you want.

**Comment by SyntaxPolice** [comment]
Working directly with reporter in private email to examine use of Tozny's library.

Based on my review of the reporter's code, I see a hard-coded password sent through several layers of constructors, eventually into the code that generates a key from a password. I also see a hard-coded salt instead of our random salt generator. Will confirm with reporter. If this is the case, it indicates an error in the use of the library, not an error in the library.

I [updated the readme](https://github.com/tozny/java-aes-crypto/blob/master/README.md#generate-a-key-from-a-password-or-passphrase) with more specific examples.

**Comment by SyntaxPolice** [comment]
Since I haven't heard back from the reporter, and this looks like a but in their application, I'm going to close this report. If you have further issues, or you think it's a bug in the Tozny library, please re-open. Thanks!

**Comment by GiaGioi99** [comment]
@SyntaxPolice hi, We were having a similar problem, but we tried to search for the class that google warning sent us but it didn't. I wonder if you can help us.
![image](https://user-images.githubusercontent.com/60766646/81476506-7b25f680-923c-11ea-8acc-ce135959f670.png)

**Comment by SyntaxPolice** [comment]
Are you using our AES library? Look for the part of the code where you
create the encryption keys. If it has a fixed password then that's the
problem.
