### ISSUE TITLE
Maven support

### ISSUE THREAD

**Issue by orhanobut** [tozny/java-aes-crypto#7]
It will be great to put this project as jar into the maven central, thus we can use it via dependency and for each update, we can get it immediately at least. Currently we need to copy/paste.

I really like this repo :)

**Comment by swenson** [comment]
Do people use Maven with Android dependencies? I'm not opposed to publishing there, though it is quite a hassle.

Our goal was to have a self-contained `.java` file that was easy to copy and paste. :)

**Comment by orhanobut** [comment]
Actually yea, people use maven central quite often. But it is hassle indeed. I would at least suggest to have release versions, thus we can differentiate easily. :)

**Comment by SyntaxPolice** [comment]
Thanks, @orhanobut. We'll work on that!

**Comment by scottyab** [comment]
Hey guys, dunno if you wanna check out my [fork](https://github.com/scottyab/java-aes-crypto) I've refactored in to Android library project and published a snapshot build to maven central for very easy one liner include for devs using Android studio/gradle. I've recently jumped through the hoops of publishing to maven central so it was quite a straightforward process. 

If it's preferable rather than to you guys setting up accounts with sonatype.org I'm happy to push this to live maven and then PR these changes to the main repo. Alternatively you could use this fork as an guide.

**Comment by SyntaxPolice** [comment]
scottyab, thanks so much for doing this. Really appreciate it. It would be nice to have it under our account instead of yours, as you mentioned.

One of the goals of the library was to make it easy to copy-paste. This refactoring is great from a software engineering standpoint, but I wonder if it'll make it harder for the unwashed masses. Just a thought. Any opinions on that?

**Comment by scottyab** [comment]
It's still copy and pasteable IMO as there aren't any additional dependancies, just a few extra clicks down the standard Android/gradle folder hierarchy which will be familiar to most Android devs. However maybe we include near the top of the readme something along the lines of "just wanna copy and paste into you're project? click here" which links direct to AesCbcWithIntegrity.java. I'd also say once published to maven central it's even easier to add the dependancy rather than copy/paste the code. 

Recent article I've written on [publishing to maven central](http://intohand.com/blog/post/how-to-publish-your-open-source-library-to-maven-central)

**Comment by orhanobut** [comment]
I'd say maven is really great to get the latest update whenever possible. If not, at least release builds would be great to see the changes. Currently if you make any changes, no one will notice easily.

**Comment by scottyab** [comment]
Good point about updates @orhanobut, @SyntaxPolice i've updated my version of the [readme](https://github.com/scottyab/java-aes-crypto/blob/master/README.md) to try and explain what i meant

**Comment by SyntaxPolice** [comment]
You guys rock. Thanks for all the help. I'll tackle this ASAP. Out of interest, is there a good way to produce and publish the javadoc as part of this process?

**Comment by jitpack-io** [comment]
Would be trivially easy to publish to https://jitpack.io. Don't even need to upload anything:) All that's needed is a GitHub release and a build file. Happy to submit a PR with a Gradle or Maven build file if you're interested

**Comment by sanindya-iiitd** [comment]
Hi @SyntaxPolice,
Thank you for making this git repository and the corresponding video. I found it quite helpful.

I was trying to use your library by adding the 'com.tozny:aes-crypto:0.0.1' to my gradle dependencies but Android Studio couldn't find the library on Maven Central. Then, I came across this discussion.
I've now updated the dependency to 'com.scottyab:aes-crypto:0.0.3'. 

I request you to please edit the README file and mention that currently one should put 'com.scottyab:aes-crypto:0.0.3' in the gradle file instead of 'com.tozny:aes-crypto:0.0.1'.

For people who are simply looking for a library that works (given that many libraries are available), adding one line in gradle does the trick. Thanks again!

**Comment by devTechi** [comment]
@sanindya-iiitd me too.

now trying to add `compile 'com.scottyab:aes-crypto:0.0.4'`
thanks anyway for the class and any work.
